# Site settings
title: Walking On Travels
description: This website is showing you the beautiful landscapes, arcbitectures and landmarks our world has..
cover: desktop/bali.jpg
logo: desktop/logo.jpg
favicon: assets/images/favicon.png
baseurl: "/hanuman/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://aleynapolat20.github.io" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
instagram: instgram

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: AleynaPolat20 #github username
repo: TravelBlog #github repository
branch: master #branch
relative_source: ../TravelBlog/ #source directory
destination: ../TravelBloge - page/ #destination directory
production_url:  https://AleynaPolat20.com/
source_url:  https://github.com/AleynaPolat20/TravelBlog #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
